/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DefaultComponent {
        "startTime": number;
    }
}
declare global {
    interface HTMLDefaultComponentElement extends Components.DefaultComponent, HTMLStencilElement {
    }
    var HTMLDefaultComponentElement: {
        prototype: HTMLDefaultComponentElement;
        new (): HTMLDefaultComponentElement;
    };
    interface HTMLElementTagNameMap {
        "default-component": HTMLDefaultComponentElement;
    }
}
declare namespace LocalJSX {
    interface DefaultComponent {
        "startTime"?: number;
    }
    interface IntrinsicElements {
        "default-component": DefaultComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "default-component": LocalJSX.DefaultComponent & JSXBase.HTMLAttributes<HTMLDefaultComponentElement>;
        }
    }
}
